### register
POST http://localhost:3333/auth/register HTTP/1.1
content-type: application/json

{
  "name": "rogerio",
  "email": "rogerio@gmail.com",
  "password": "123456"
}

### authentication
POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

{
  "email": "rogerio@gmail.com",
  "password": "123456"
}

### logout
GET http://localhost:3333/auth/logout HTTP/1.1
cookie: authUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjNkODU4Y2QtNWVmMy00ODI0LTgyOTMtOGNmNGU1ODc5MzI5IiwibmFtZSI6InJvZ2VyaW8iLCJlbWFpbCI6InJvZ2VyaW9AZ21haWwuY29tIn0sImlhdCI6MTcxODA4MDAzOSwiZXhwIjoxNzE4NTk4NDM5fQ.59ZbaeAzlCkzN80cb7FC0LdJ4-IffJiKpU9Y0GZ2hHM
content-type: application/json


### list projects
GET http://localhost:3333/projects HTTP/1.1
cookie: authUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjNkODU4Y2QtNWVmMy00ODI0LTgyOTMtOGNmNGU1ODc5MzI5IiwibmFtZSI6InJvZ2VyaW8iLCJlbWFpbCI6InJvZ2VyaW9AZ21haWwuY29tIn0sImlhdCI6MTcxODEzNzgyMiwiZXhwIjoxNzE4NjU2MjIyfQ.Rq_8ipsL_-QEmxATf5AS_RWdeaLJzg-NiX5TmTlFnd8
content-type: application/json


### list project
GET http://localhost:3333/projects/0d66773e-8099-4241-87c3-066669394453 HTTP/1.1
cookie: authUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjNkODU4Y2QtNWVmMy00ODI0LTgyOTMtOGNmNGU1ODc5MzI5IiwibmFtZSI6InJvZ2VyaW8iLCJlbWFpbCI6InJvZ2VyaW9AZ21haWwuY29tIn0sImlhdCI6MTcxODA3ODgzMiwiZXhwIjoxNzE4NTk3MjMyfQ.pz3u49rrq6KSJV-reap7JkcKRSu_QBZ59-Iw8Pb2uUY
content-type: application/json



### create project
POST http://localhost:3333/projects HTTP/1.1
content-type: application/json
cookie: authUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjNkODU4Y2QtNWVmMy00ODI0LTgyOTMtOGNmNGU1ODc5MzI5IiwibmFtZSI6InJvZ2VyaW8iLCJlbWFpbCI6InJvZ2VyaW9AZ21haWwuY29tIn0sImlhdCI6MTcxODA3NDExMSwiZXhwIjoxNzE4NTkyNTExfQ.ef-qTSP1NP_KZBSUu2Qx2OBoXRqTNFEMSAS50Y_aCz4

{
  "name": "primeiro projeto"
}


### update project
PUT http://localhost:3333/projects/699f06d8-ff41-412c-8ee6-861cb9c18c0b HTTP/1.1
content-type: application/json
cookie: authUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjNkODU4Y2QtNWVmMy00ODI0LTgyOTMtOGNmNGU1ODc5MzI5IiwibmFtZSI6InJvZ2VyaW8iLCJlbWFpbCI6InJvZ2VyaW9AZ21haWwuY29tIn0sImlhdCI6MTcxNzM0ODQ1NSwiZXhwIjoxNzE3ODY2ODU1fQ.88C3vbdn4Gwrg-93dNV0Q-Y_4SlMxsStdTujDYB-xAw

{
  "html": "<h1>Hello world</h1>",
  "css": "h1 { color: red; }"
}


### delete project
DELETE http://localhost:3333/projects/699f06d8-ff41-412c-8ee6-861cb9c18c0b HTTP/1.1
content-type: application/json
cookie: authUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjNkODU4Y2QtNWVmMy00ODI0LTgyOTMtOGNmNGU1ODc5MzI5IiwibmFtZSI6InJvZ2VyaW8iLCJlbWFpbCI6InJvZ2VyaW9AZ21haWwuY29tIn0sImlhdCI6MTcxNzM0ODQ1NSwiZXhwIjoxNzE3ODY2ODU1fQ.88C3vbdn4Gwrg-93dNV0Q-Y_4SlMxsStdTujDYB-xAw
